version: '3'
services:
  mf_drawer:
    build: ./mf_drawer
    ports:
      - "3000:80"

  mf_videos:
    build: ./mf_videos
    ports:
      - "3001:80"

  bff:
    build: ./bff
    ports:
      - "3002:3002"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./bff/src:/app/src
